# name: Go Linter

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   linter:
#     name: Lint Go code
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.17

#     - name: Lint Go Code
#       uses: golangci/golangci-lint-action@v2
#       with:
#         version: v1.41.1
